package dk.nodes.nstack.kotlin

const val localizeResourceJson =
    "{\"data\":[{\"id\":16,\"url\":\"https:\\/\\/nstack-staging.vapor.cloud\\/api\\/v2\\/content\\/localize\\/resources\\/16\",\"last_updated_at\":\"2019-11-06T04:28:43+00:00\",\"should_update\":true,\"language\":{\"id\":11,\"name\":\"English (UK)\",\"locale\":\"en-GB\",\"direction\":\"LRM\",\"is_default\":true,\"is_best_fit\":false}},{\"id\":249,\"url\":\"https:\\/\\/nstack-staging.vapor.cloud\\/api\\/v2\\/content\\/localize\\/resources\\/249\",\"last_updated_at\":\"2019-11-06T04:28:43+00:00\",\"should_update\":true,\"language\":{\"id\":14,\"name\":\"Spanish (Spain)\",\"locale\":\"es-ES\",\"direction\":\"LRM\",\"is_default\":false,\"is_best_fit\":false}},{\"id\":307,\"url\":\"https:\\/\\/nstack-staging.vapor.cloud\\/api\\/v2\\/content\\/localize\\/resources\\/307\",\"last_updated_at\":\"2019-11-06T04:28:43+00:00\",\"should_update\":true,\"language\":{\"id\":6,\"name\":\"Danish\",\"locale\":\"da-DK\",\"direction\":\"LRM\",\"is_default\":false,\"is_best_fit\":true}}]}"
const val localizeUrlEnUk =
    "{\"data\":{\"default\":{\"ok\":\"Ok\",\"cancel\":\"__cancel\",\"no\":\"__no\",\"yes\":\"__yes\",\"retry\":\"__retry\",\"edit\":\"__edit\",\"save\":\"__save\",\"back\":\"__back\",\"settings\":\"__settings\",\"later\":\"__later\",\"next\":\"__next\",\"previous\":\"__previous\",\"skip\":\"__skip\"},\"versionControl\":{\"updateHeader\":\"New version is out, please update\",\"forceHeader\":\"New version is out, you have to update!\",\"negativeBtn\":\"Cancel\",\"positiveBtn\":\"Update\",\"newInVersionHeader\":\"New in this version\",\"okBtn\":\"Ok\"},\"rateReminder\":{\"title\":\"Rate the app\",\"body\":\"We can see you like the application. Would you like to rate it?\",\"yesBtn\":\"Yes\",\"laterBtn\":\"Later\",\"noBtn\":\"No\"},\"error\":{\"authenticationError\":\"__authenticationError\",\"connectionError\":\"__connectionError\",\"errorTitle\":\"__errorTitle\",\"unknownError\":\"__unknownError\"},\"messages\":{\"okBtn\":\"Ok\",\"urlBtn\":\"Open URL\"}},\"meta\":{\"language\":{\"id\":11,\"name\":\"English (UK)\",\"locale\":\"en-GB\",\"direction\":\"LRM\",\"is_default\":false,\"is_best_fit\":false},\"platform\":{\"id\":12,\"slug\":\"mobile\"}}}"
const val localizeUrlEsEs =
    "{\"data\":{\"default\":{\"ok\":\"Ok\",\"cancel\":\"__cancel\",\"no\":\"__no\",\"yes\":\"__yes\",\"retry\":\"__retry\",\"edit\":\"__edit\",\"save\":\"__save\",\"back\":\"__back\",\"settings\":\"__settings\",\"later\":\"__later\",\"next\":\"__next\",\"previous\":\"__previous\",\"skip\":\"__skip\"},\"versionControl\":{\"updateHeader\":\"Nueva version disponible, por favor actualiza\",\"forceHeader\":\"Nueva version disponible, tienes que actualizar!\",\"negativeBtn\":\"Cancelar\",\"positiveBtn\":\"Actualizar\",\"newInVersionHeader\":\"Nuevo en esta version\",\"okBtn\":\"Ok\"},\"rateReminder\":{\"title\":\"Valora la app\",\"body\":\"Vemos que te gusta la aplicaci\\u00f3n.\\r\\nQuieres valorarla?\",\"yesBtn\":\"Si\",\"laterBtn\":\"Despu\\u00e9s\",\"noBtn\":\"No\"},\"error\":{\"authenticationError\":\"__authenticationError\",\"connectionError\":\"__connectionError\",\"errorTitle\":\"__errorTitle\",\"unknownError\":\"__unknownError\"},\"messages\":{\"okBtn\":\"__okBtn\",\"urlBtn\":\"__urlBtn\"}},\"meta\":{\"language\":{\"id\":14,\"name\":\"Spanish (Spain)\",\"locale\":\"es-ES\",\"direction\":\"LRM\",\"is_default\":false,\"is_best_fit\":false},\"platform\":{\"id\":12,\"slug\":\"mobile\"}}}"
const val localizeUrlDaDk =
    "{\"data\":{\"default\":{\"ok\":\"Ok\",\"cancel\":\"Annuller\",\"no\":\"Nej\",\"yes\":\"Ja\",\"retry\":\"Pr\\u00f8v igen\",\"edit\":\"Rediger\",\"save\":\"Gem\",\"back\":\"Tilbage\",\"settings\":\"Indstillinger\",\"later\":\"Senere\",\"next\":\"N\\u00e6ste\",\"previous\":\"Forrige\",\"skip\":\"Spring over\"},\"versionControl\":{\"updateHeader\":\"Ny version er ude\",\"forceHeader\":\"Ny version er ude, du skal opdatere!\",\"negativeBtn\":\"Annuller\",\"positiveBtn\":\"Opdater\",\"newInVersionHeader\":\"Nyt i denne version\",\"okBtn\":\"Ok\"},\"rateReminder\":{\"title\":\"__title\",\"body\":\"__body\",\"yesBtn\":\"__yesBtn\",\"laterBtn\":\"__laterBtn\",\"noBtn\":\"__noBtn\"},\"error\":{\"authenticationError\":\"Login er udl\\u00f8bet, login venligst ind igen.\",\"connectionError\":\"Ingen eller d\\u00e5rlig forbindelse, pr\\u00f8v igen.\",\"errorTitle\":\"Fejl\",\"unknownError\":\"Ukendt fejl, pr\\u00f8v igen.\"},\"messages\":{\"okBtn\":\"__okBtn\",\"urlBtn\":\"__urlBtn\"}},\"meta\":{\"language\":{\"id\":6,\"name\":\"Danish\",\"locale\":\"da-DK\",\"direction\":\"LRM\",\"is_default\":false,\"is_best_fit\":false},\"platform\":{\"id\":12,\"slug\":\"mobile\"}}}"

