package dk.nodes.nstack.demo

import dk.nodes.nstack.kotlin.NStack

/**
 * generated by nstack gradle plugin on Thu Oct 24 22:39:33 CEST 2019
 */
object RateReminderActions {

	private const val RIDE_COMPLETED = "ride-completed"

	suspend fun rideCompleted() {
		send(RIDE_COMPLETED)
	}

	private suspend fun send(action: String) {
		NStack.RateReminder.action(action)
	}
}
