package dk.nodes.nstack.demo

import dk.nodes.nstack.kotlin.NStack

/**
 * Generated by the NStack gradle plugin
 */
object RateReminderActions {

    private const val FIRSTACTION = "firstaction"
    private const val SECONDACTION = "secondaction"

    suspend fun firstaction() {
        send(FIRSTACTION)
    }

    suspend fun secondaction() {
        send(SECONDACTION)
    }

    private suspend fun send(action: String) {
        NStack.RateReminder.action(action)
    }
}
